### ISSUE TITLE
How would I replay past events using this component?

### ISSUE THREAD

**Issue by rsoesemann** [TheVishnuKumar/lwc-streaming-api#3]
In empApi there is a parameter to replay past events. https://developer.salesforce.com/docs/component-library/bundle/lightning-emp-api/documentation

Can I also do it using this component?

**Comment by TheVishnuKumar** [comment]
At this moment no, This component is inspired by this https://developer.salesforce.com/docs/atlas.en-us.api_streaming.meta/api_streaming/code_sample_generic_vfp_walkthrough.htm.

This component can be updated based on the replay. It needs another extension for it https://github.com/developerforce/SalesforceDurableStreamingDemo/blob/master/staticresources/cometdReplayExtension.resource.
